### ISSUE TITLE
ActionBar Custom Title View not supported

### ISSUE THREAD

**Issue by GERJohnson** [rigor789/nativescript-vue#56]
Below link says that the ActionBar can have a custom title view. If I use it with nativescript-vue the StackLayout within the ActionBar is ignored and the text tag is pulled

https://docs.nativescript.org/ui/action-bar#using-a-custom-title-view

**Comment by rigor789** [comment]
I have pushed some changes to the way the renderer works, can you give it a try and let me know if it works for you? A simple example with a custom label + formatted string works for me!

Update to `nativescript-vue@0.1.11`

**Comment by GERJohnson** [comment]
it is still not working for me. I tried it even with a fresh installation. what is your code?

**Comment by rigor789** [comment]
Here's the code I'm using: https://github.com/rigor789/nativescript-vue/blob/master/samples/app/app-with-tab-view.js#L15-L25

**Comment by GERJohnson** [comment]
nope doesn't work either on iOS

**Comment by rigor789** [comment]
I have created a little example with the latest code of ns-vue (not released or pushed out yet, need to test a few more cases before it's ready)...

https://play.nativescript.org/?template=play-vue&id=dlfx20OfH00hd-h0Qs8Z0

Can you show me your current code you are using? The issue might be the letter casing (that's what my latest code fixes / improves hence the ridiculous casing in the example)

**Comment by GERJohnson** [comment]
```
import Vue from 'nativescript-vue'

let app = new Vue({

    template: `
        <page>
            <action-bar title="OLD TITLE">
              <stack-layout>
                <image src="res://icon" style="width: 30; height: 30; vertical-align: center; margin-right: 10;"> </image>
                <label style="font-size: 20; vertical-align: center;"> NEW TITLE </label>
              </stack-layout>
            </action-bar>
            <stack-layout>
                <label> CONTENT </label>
            </stack-layout>
        </page>
    `
})

app.$start()
```
<img width="420" alt="screen shot 2017-10-04 at 23 37 41" src="https://user-images.githubusercontent.com/21923568/31200933-0a1f4f42-a95d-11e7-9fdd-b70b94b6ca51.png">

**Comment by rigor789** [comment]
Looks like it works fine in the newest version, so once I finish it, I'll let you know! I think I can finish it in the next 10 minutes haha!

https://play.nativescript.org/?template=play-vue&id=8uGvlYbBNw0Wb3B62gcW0

**Comment by GERJohnson** [comment]
hm..  if I use this link on my iPhone 7 via playground app I still get the old title..  do you test it on IOS?

**Comment by rigor789** [comment]
No I can't test on iOS unfortunately.

**Comment by rigor789** [comment]
Can you give `nativescript-vue@0.1.15` a try?

**Comment by rigor789** [comment]
Should be all fixed in `v0.1.21`

**Comment by GERJohnson** [comment]
yes works now 👍
