### ISSUE TITLE
Action bar title is not shown on iOS

### ISSUE THREAD

**Issue by vhristov5555** [rigor789/nativescript-vue#60]
code:
```
const Vue = require("./nativescript-vue");

new Vue({
  template: `
    <page>
           <action-bar title="title">
            </action-bar>
            <label text="Label"></label>
    </page>
  `,

}).$start();
```

Actual: The action bar title is not shown on iOS
Expected: The action bar title to be shown on iOS

Comment: It works on 0.1.10 verion. It works on Android all version i have tested.

**Comment by alekspetrov** [comment]
+1

**Comment by rigor789** [comment]
Should be fixed in `v0.1.21`

**Comment by alekspetrov** [comment]
I'm on v0.7.8 and <action-bar> still not showing =( How to fix that?
